# Generated by Django 2.2.13 on 2020-06-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200609_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftuser',
            name='coalition_point',
        ),
    ]
