# Generated by Django 3.1 on 2020-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200819_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftuser',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
