# Generated by Django 2.2.13 on 2020-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_see_piscine',
            field=models.BooleanField(default=False),
        ),
    ]
