# Generated by Django 3.1 on 2020-08-19 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200804_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.CharField(blank=True, max_length=100, null=True)),
                ('github_id', models.IntegerField(blank=True, null=True)),
                ('github_bio', models.TextField(blank=True, null=True)),
                ('github_html_url', models.URLField(blank=True, null=True)),
                ('github_avatar_url', models.URLField(blank=True, null=True)),
                ('github_total_star', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
