# Generated by Django 2.2.13 on 2020-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiscineProject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='과제 이름')),
            ],
        ),
        migrations.CreateModel(
            name='TempFtUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PiscineFtUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=20, verbose_name='로그인 아이디')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개여부')),
                ('piscine_level', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='피씬레벨')),
                ('peer_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='피어평가횟수')),
                ('pool_year', models.CharField(max_length=5)),
                ('pool_month', models.CharField(max_length=10)),
                ('is_pass', models.BooleanField(default=False, verbose_name='합격여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('piscine_projects', models.ManyToManyField(blank=True, to='piscine.PiscineProject')),
            ],
        ),
    ]
