# Generated by Django 2.2.13 on 2020-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscineftuser',
            name='piscine_projects',
            field=models.ManyToManyField(blank=True, null=True, to='piscine.PiscineProject'),
        ),
    ]
