# Generated by Django 2.2.13 on 2020-06-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0002_auto_20200607_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscineftuser',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='공개여부'),
        ),
    ]
