# Generated by Django 2.2.13 on 2020-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0004_auto_20200607_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscineftuser',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
    ]
