# Generated by Django 2.2.13 on 2020-06-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0005_auto_20200607_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFtUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
