# Generated by Django 2.2.13 on 2020-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0006_tempftuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscineftuser',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='합격여부'),
        ),
    ]
