# Generated by Django 2.2.13 on 2020-07-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0007_piscineftuser_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscineftuser',
            name='peer_count',
            field=models.IntegerField(default=0, verbose_name='피어평가횟수'),
        ),
    ]
