# Generated by Django 3.0.6 on 2020-05-12 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='길드 이름')),
                ('color', models.CharField(max_length=7, verbose_name='길드 색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FtUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=20, verbose_name='로그인 아이디')),
                ('is_alive', models.BooleanField(default=False, verbose_name='생존여부')),
                ('coalition_point', models.IntegerField(blank=True, null=True, verbose_name='길드 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coalition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coalition', verbose_name='길드')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_updating', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coalition_point', models.IntegerField(verbose_name='길드 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ft_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FtUser')),
                ('update_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UpdateBranch')),
            ],
        ),
    ]
