# Generated by Django 3.1 on 2020-08-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_apikey_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coalition_point', models.IntegerField(verbose_name='길드 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ft_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ftuser')),
            ],
        ),
        migrations.DeleteModel(
            name='PointLog',
        ),
        migrations.DeleteModel(
            name='UpdateBranch',
        ),
    ]
